### ISSUE TITLE
Distributed Computing

### ISSUE THREAD

**Issue by PNaughton** [UCSD-E4E/stingray-auv#10]
Set up a talker-listener system across N number of machines. This will also help us experiment faster, help with demos, etc.

**Comment by PNaughton** [comment]
I.e. it would be nice to be able to run stereo image software on the desktop while pulling the imu data from the imu connected to the atom board. I am not sure what are data rate limitations are on this, but we should push them

**Comment by antonellla** [comment]
I'd try running all the processes on each machine in their own namespace (i.e. processes on the stingray will have the globally resolved namespace /stingray/stereo/left/.... ). Then any of the processes on any of the machines on the network can be accessed through the globally resolved hostname.  No need to ssh or any of that.

This is helpful: http://www.ros.org/wiki/Names

**Comment by PNaughton** [comment]
Thanks that is helpful. It still may be helpful to figure this out so that we can launch processes on different machines using a single launch file. Do you know if this is possible?

**Comment by antonellla** [comment]
Almost 100% sure it is not only possible but very easy.  All you need is the IPs or hostnames, then it knows where to launch each process, and what namespace to launch each process in.

**Comment by PNaughton** [comment]
Cool. Lets try! I envision being able to pull IMU data to the desktop through the atom, so that we can do testing that way.

**Comment by PNaughton** [comment]
Thomas did a lot for us. Still need to set up the i7
