### ISSUE TITLE
Write os5000 Driver

### ISSUE THREAD

**Issue by PNaughton** [UCSD-E4E/stingray-auv#18]
We have a compass that we are not using because there is not a driver for it.

**Comment by PNaughton** [comment]
This might already be done. Can you verify this? I think that we are just missing callbacks where they are needed and an appropriate way to use the data in conjunction with the IMU

**Comment by omirbod** [comment]
Looks like the driver is already written, it's under os5000, and i see a
couple of topics being published when you run the node. Still trying to
figure out how to output the data though to the screen

**Comment by omirbod** [comment]
The driver right now for the os5000 reads the accelerometer, temperature,
and depth, so I will need to add the magnetic field reading to get
published.

**Comment by omirbod** [comment]
sorry I meant it's currently reading roll/pitch/yaw angles, temperature,
and depth.

**Comment by omirbod** [comment]
Hey Everyone,
I have attached the tutorial code and some instructions on how to get
started with the compass and ROS. I Will make a more extensive
documentation after this weekend, but this should be enough if you want to
get started and test out your ROS installation. Let me know if you have any
questions.

Thanks,
Omeed

**Comment by eduardoramirez** [comment]
Hey Omeed,

I wanted to know when is a good time for me to come in next week? I want to get started doing something, I have been going over the tutorials and I feel ready to start now.

Thank you,
Eduardo

**Comment by omirbod** [comment]
Hi Eduardo,
I'm glad you have been going over the tutorials. I'm available during the
times posted on this calendar(usually after 6pm and all day Wednesday):
http://www.when2meet.com/?1199541-WQlki

If you haven't done so already, you should also fill out the times that you
are available on the calendar, that way it will be easier for us to arrange
for a time to meet up in smaller groups to work on tasks.

Just send me a quick email when you plan to come in, and I'll make sure to
be there in the lab to get you started.

Thanks,
Omeed
